### ISSUE TITLE
 Divided by zero

### ISSUE THREAD

**Issue by toppyishappy** [sohaib023/siamese-pytorch#1]
There is some error with divided by zero because of empty losses list and initial total=0.
![image](https://user-images.githubusercontent.com/40524345/163220415-b0d0200b-9089-418b-91ea-51a660b36e3f.png)

**Comment by sohaib023** [comment]
Its trying to divide by the number of training samples which in this case seem to be zero. I would add a check there, to circumvent the division by zero error, but for your purposes, I would suggest to double check the path and see if it has the images in the specified format.

**Comment by toppyishappy** [comment]
It is my fault because the images need to be png.

**Comment by toppyishappy** [comment]
It is my fault because the images need to be png.
