### ISSUE TITLE
Student project : asking for permissions and datasets

### ISSUE THREAD

**Issue by ClixTOUT** [sohaib023/siamese-pytorch#3]
Dear author of this repository,

I'm a french IT engineering student, working on a school project consisting of optimizing
an already existing deep learning program for key points detection.

I find your code very interesting, and would like to have your _permission for using it_ in 
an educational purpose, and would like to _get your datasets_ if you still have it ?

Here is my email address : mehdi.elidrissi89@gmail.com

Thank you in advance for your response,

Cordially.

EL IDRISSI Mehdi

**Comment by sohaib023** [comment]
Hello Mehdi,

I'm glad to see that you are interested in this project. Unfortunately, the datasets were a part of a client project and hence I cannot share it. However, it was a fairly small and simple dataset with roughly 10 different persons with 10-20 images per person.
If you have any other questions I would be glad to help.

Best, Sohaib.

**Comment by ClixTOUT** [comment]
Hello,

Thanks for your reply. Good luck on your work.

Best regards,

Mehdi
